proxy-wasm/proxy-wasm-cpp-host

- .bazelrc
- .clang-format
- BUILD
- WORKSPACE
- context_test.cc
- include/proxy-wasm/compat.h
- include/proxy-wasm/context.h
- include/proxy-wasm/wasm_vm.h
- include/proxy-wasm/word.h
- wasm_vm_test.cc
This incorporates the changes from the review branches and it removes the Envoy
specific BUILD file (which will be stored in the envoy repo) in favor of a generic BUILD
file for testing just this repo.
> Update with respect to review branches.

- BUILD
- context_test.cc
- include/proxy-wasm/context.h
- src/base64.cc
- src/base64.h
- wasm_vm_test.cc
> Fix issue with logging on root contexts.

- .github/workflows/cpp.yml
- BUILD
- WORKSPACE
- include/proxy-wasm/context.h
- include/proxy-wasm/exports.h
- include/proxy-wasm/null_plugin.h
- include/proxy-wasm/wasm.h
- include/proxy-wasm/wasm_api_impl.h
- include/proxy-wasm/wasm_vm.h
- include/proxy-wasm/word.h
- src/context.cc
- src/exports.cc
- src/null/null_plugin.cc
- src/wasm.cc
> Changes for integration into proxy-wasm.

- include/proxy-wasm/null_plugin.h
- include/proxy-wasm/wasm_api_impl.h
- src/null/null_plugin.cc
Same fix as https://github.com/istio/envoy/pull/183, which is missing here.
> add getContext function to the Null Vm

- src/context.cc
> Cleanup and document Context::onStart.

- WORKSPACE
- src/context.cc
This adds support to the new status values added by the
proxy-wasm-cpp-sdk in
https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/19
It won't build until that is also merged.
> Properly convert all headers statuses returned by the WASM.

- include/proxy-wasm/wasm.h
- include/proxy-wasm/word.h
- src/null/null_plugin.cc
- src/v8/v8.cc
- src/wasm.cc
- src/wavm/wavm.cc
> Handle error cases gracefully. WASM -> Wasm.

- include/proxy-wasm/context.h
- include/proxy-wasm/context_interface.h
- src/context.cc
Add the "end_of_stream" flag to onRequestHeaders and
onResponseHeaders to match the signature in Envoy. It's ignored
for new. We'll use another commit to pass this field on to WASM.
This begins to address:
https://github.com/envoyproxy/envoy-wasm/issues/446
> Add the "end_of_stream" flag to header processing.

- WORKSPACE
- include/proxy-wasm/null_plugin.h
- include/proxy-wasm/wasm.h
- src/context.cc
- src/null/null_plugin.cc
This propagates the end_of_stream flag to the plugin for both the header callbacks. It is an incompatible change -- modules will need to be recompiled once this is merged into Envoy.
This makes is possible for a filter to deal with request and response bodies in a generic way without having to guess whether a body is coming from the HTTP method. This is important because otherwise a filter might wait for an "on data" callback that will never come.
I'll submit the matching PRs for the other two repos once this one is merged.
> Pass end_of-stream flag to request and response headers.

- src/exports.cc
> Remove bad check during buffer write.

- WORKSPACE
- include/proxy-wasm/context.h
- include/proxy-wasm/context_interface.h
- include/proxy-wasm/exports.h
- include/proxy-wasm/null_plugin.h
- include/proxy-wasm/wasm.h
- include/proxy-wasm/wasm_api_impl.h
- include/proxy-wasm/wasm_vm.h
- include/proxy-wasm/word.h
- src/context.cc
- src/exports.cc
- src/null/null_plugin.cc
- src/wasm.cc
> Enable onForeignFunction and proxy-specific extensions to the ABI.

- include/proxy-wasm/null_plugin.h
- src/null/null_plugin.cc
and add missing constructor from context registery for Null VM.
> Add support for more WASM_EXPORT overrides in the Null VM

- src/context.cc
The "onQueueReady" callback was never called when enqueuing to
a shared queue because the code was using vm_id to look up the
thread-local WASM instance in a hash table that was indexed by
vm_key. Now the "on ready" callback is propery fired.
Merging this into envoy-wasm will require a test change there.
> Fix selection of thread-local wasm when enqueuing

- include/proxy-wasm/context.h
- include/proxy-wasm/context_interface.h
- include/proxy-wasm/exports.h
- src/exports.cc
- src/wasm.cc
The intent of this function is to return the current log level
in the host. This way, WASM modules can avoid calling proxy_log
at all for certain log levels if they are sure that nothing
will be logged.
This will be important in WASM modules that wish to support "debug"
and "trace" logging but which also want to reduce the cost of
generating log messages that will never be output.
If this makes sense to you all then I'll make the appropriate changes
in the SDK and in envoy-wasm too.
> Begin to add support for a proxy_get_log_level ABI function

- include/proxy-wasm/wasm_api_impl.h
This was missing from the code I put in a while back to support this new function.
> Add proxy_get_log_level to the NullVm

- include/proxy-wasm/context.h
- include/proxy-wasm/context_interface.h
- include/proxy-wasm/exports.h
- include/proxy-wasm/null_plugin.h
- include/proxy-wasm/null_vm.h
- include/proxy-wasm/wasm.h
- include/proxy-wasm/wasm_api_impl.h
- include/proxy-wasm/wasm_vm.h
- src/context.cc
- src/exports.cc
- src/null/null_plugin.cc
- src/null/null_vm.cc
- src/v8/v8.cc
- src/wasm.cc
- src/wavm/wavm.cc
> Support multiple versions of the Proxy-Wasm ABI.

- include/proxy-wasm/wasm_vm.h
- src/null/null_vm.cc
- src/v8/v8.cc
- src/wasm.cc
Add ProxyWasm_0_2_1 enum and support.
> Move get_log_level to ABI version 0.2.1

- src/wasm.cc
- src/wavm/wavm.cc
> Fix WAVM support.

- src/exports.cc
This convention is already allowed in proxy_set_buffer_bytes(),
and it was previously allowed for proxy_get_buffer_byts().
> Allow proxy_get_buffer_byts(0, MAX, ...).

- include/proxy-wasm/context.h
> Do not use get_clock on windows where it is not supported.

- include/proxy-wasm/exports.h
- src/exports.cc
Signed-off-by: Kuat Yessenov <kuat@google.com>
> export pair marshalling

- include/proxy-wasm/exports.h
- src/exports.cc
Signed-off-by: Kuat Yessenov <kuat@google.com>
> move to header files

- src/wasm.cc
Cloned VM doesn't (always) have a copy of the bytecode,
so initialize it using bytecode from the base VM.
Note that we don't have NotCloneable runtime right now.
> Fix initialization of NotCloneable VMs.

- include/proxy-wasm/exports.h
- include/proxy-wasm/wasm_vm.h
- src/exports.cc
- src/wasm.cc
this PR implements WASI's `clock_time_get`. Some of languages assume that clock_time_get is available in the host for their runtime or their standard libraries. I think it's plausible to implement this now (I know in the next version of ABI `get_current_time_nanoseconds` is removed and we are encouraged to use this `clock_time_get`).
___
> export wasi_clock_time_get

- src/context.cc
Fix the bug in using a same`wasm` file for multiple times with a same VM ID:
- `on_context_create_` is invoked only for the first root context (this is because `on_context_create_` is executed in onStart)
-  `onConfigure` is executed for the other root contexts without invoking `on_context_create_`,
As far as I know, this results in panics in [Rust](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/master/src/dispatcher.rs#L210) and [TinyGo](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxywasm/abi_configuration.go#L31) SDKs, and is not the intended behavior.
___
> invoke on_context_create_ for all root contexts with a same VM ID

- include/proxy-wasm/wasm.h
- src/wasm.cc
> Remove no longer needed Emscripten metadata.

- include/proxy-wasm/wasm.h
- src/null/null_plugin.cc
- src/wasm.cc
> Add support for the _initialize() crt1 startup function.

- include/proxy-wasm/wasm.h
- src/wasm.cc
Previously, getRootContext() was adding an empty entry to the map.
> Fix getRootContext().

- src/wasm.cc
On some targets (e.g. Rust's wasm32-wasi), it's impossible to export
malloc due to a collision with libc's malloc.
> Use proxy_on_memory_allocate() as a fallback for malloc().

- src/wavm/wavm.cc
this fixes segfault when an exception happens in a cloned VM 
> wavm: clone integration in Wavm::clone()

- src/v8/v8.cc
resolves #74 
the following is an example message:
```
[source/extensions/common/wasm/wasm_vm.cc:29] Bad function signature for: proxy_on_vm_start, want: i32 -> void, but the module exports: i32 i32 -> void
[source/extensions/common/wasm/wasm_vm.cc:29] Bad function signature for: proxy_on_vm_start, want: i32 i32 -> void, but the module exports: i32 i32 -> void
[source/extensions/common/wasm/wasm_vm.cc:29] Bad function signature for: proxy_on_vm_start, want: i32 -> i32, but the module exports: i32 i32 -> i32
[source/extensions/common/wasm/wasm_vm.cc:29] Bad function signature for: proxy_on_vm_start, want: i32 i32 i32 -> i32, but the module exports: i32 i32 -> i32
[source/extensions/common/wasm/wasm_vm.cc:29] Bad function signature for: …
```
> v8: enhance signature mimatch message in getModuleFunction

- src/v8/v8.cc
> Strip only Custom Sections with precompiled Wasm modules.

- src/wavm/wavm.cc
this PR emits call stack trace when exception happens in WAVM just like V8 (#66)
this requires a change in the WAVM library used in Envoy: https://github.com/envoyproxy/envoy/pull/13792
```
[2020-10-28 14:24:10.551][979699][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:29] Function proxy_on_tick failed:
WAVM message: wavm.reachedUnreachable
wasm backrace:
1: wasm!helloworld!runtime._panic+7
2: wasm!helloworld!command-line-arguments.C+2
3: wasm!helloworld!command-line-arguments.B+0
4: wasm!helloworld!command-line-arguments.A+0
5: wasm!helloworld!(*command-line-arguments.helloWorld).OnTick+74
6: wasm!helloworld!proxy_on_tick+0
```
> wavm: emit stack trace when an exception happens

- include/proxy-wasm/context.h
- include/proxy-wasm/wasm.h
- src/context.cc
- src/wasm.cc
> Allow execution of multiple instances of the same plugin.

- src/wavm/wavm.cc
> wavm: rename envoyFunction to hostFunction

- src/wavm/wavm.cc
> wavm: simplify get/register templates.

- include/proxy-wasm/context.h
- src/context.cc
- src/exports.cc
ref
- https://github.com/envoyproxy/envoy/pull/13930
- https://github.com/envoyproxy/envoy/issues/13857
> Force stop iteration after local response is sent

- include/proxy-wasm/context.h
- include/proxy-wasm/wasm.h
- src/context.cc
- src/exports.cc
ref: https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/88#issuecomment-724436498
> Clear stop_iteration_ in DeferAfterCallActions destructor

- src/context.cc
> Always process HTTP headers before processing HTTP body.

- .github/workflows/cpp.yml
> Run GitHub Actions on istio-release/** branches.

- src/shared_data.cc
- src/shared_data.h
- src/shared_queue.cc
- src/shared_queue.h
- src/vm_id_handle.cc
- test/shared_data_test.cc
- test/shared_queue_test.cc
resolves #86, envoyproxy/envoy#13835, istio/istio#27783
> Register the queue cleanup callback to vm_id handle callbacks 

- bazel/repositories.bzl
- src/v8/v8.cc
> Remove absl dependency

- include/proxy-wasm/context.h
- src/context.cc
> Fix log_prefix initialization.

- include/proxy-wasm/wasm.h
- src/wasm.cc
> Pass PluginBase to PluginHandleFactory.

- include/proxy-wasm/wasm.h
- src/null/null_plugin.cc
- src/wasm.cc
WASI reactors differ from WASI commands in that they have multiple
entrypoints (i.e. proxy_on_* callbacks) instead of only main().
Currently, each Proxy-Wasm SDK uses different approch to startup:
- AssemblyScript SDK uses Wasm's start function.
- C++ SDK creates WASI reactor with global C++ constructors taking
care of early initialization and registration of plugins.
- Rust SDK creates Wasm library, and suggests (via examples) using
_start() function called at startup to do early initialization.
Unfortunately, this is the same function name that WASI commands
are using, which means that WASI constructors cannot be injected
and executed at startup.
- TinyGo SDK creates WASI command and calls main() at startup, but
it doesn't exit after main() function returns.
Calling main() in WASI …
> Optionally call main() in WASI reactors as a convenience.

- src/exports.cc
- test/exports_test.cc
- test/test_data/env.rs
found this bug while writing tests in Envoy: it looks like `append("\x0")` or `append("\0")` does nothing, and that would result in non-terminated values in the first env vars
```
KEY1: VALUE1KEY2=VALUE2
KEY2: VALUE2
```
> Fix environ_get: append null.

- src/context.cc
> Allow using empty vm_id to indicate the current WasmVM.

- src/v8/v8.cc
This change improves performance by up to 36% in microbenchmarks.
Benchmark                                                       Diff
--------------------------------------------------------------------
WasmSpeedTest_empty                                          -0.0185
WasmSpeedTest_get_current_time                               -0.1184
WasmSpeedTest_small_string                                   -0.0081
WasmSpeedTest_small_string1000                               -0.1324
WasmSpeedTest_small_string_check_compiler                    -0.0654
WasmSpeedTest_small_string_check_compiler1000                -0.1338
WasmSpeedTest_large_string                                   -0.3187
WasmSpeedTest_large_string1000                               -0.3624
WasmSpeedTest_get_property …
> v8: use signal handlers to catch out of bounds memory access.

- src/v8/v8.cc
It's mostly a pedantic change, but it slightly improves performance
in microbenchmarks.
Benchmark                                                       Diff
--------------------------------------------------------------------
WasmSpeedTest_empty                                          -0.0891
WasmSpeedTest_get_current_time                               -0.0424
WasmSpeedTest_small_string                                   -0.0507
WasmSpeedTest_small_string1000                               -0.0118
WasmSpeedTest_small_string_check_compiler                    -0.0556
WasmSpeedTest_small_string_check_compiler1000                +0.0041
WasmSpeedTest_large_string                                   -0.0322
WasmSpeedTest_large_string1000                               -0.0311 …
> v8: avoid unnecessary log level checks.

- src/context.cc
in favor of https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/95, returns `StopAllIterationAndWatermark` to stop the further body processing in VM failure with fail_close cases.
> Return StopAllIterationAndWatermark in fail_close cases.

- include/proxy-wasm/context.h
- src/context.cc
Relevant to https://github.com/envoyproxy/envoy/issues/14947. 
Refactored around VM failure check on Http and Tcp callbacks in order to handle the VM failure right after it happens. Previously, for example, when panic happens in OnResponseHeaders, then we return Continue since we didn't check the `isFail` after the Wasm calls. That means Envoy sends the response headers to the client even if the VM fails in OnResponseHeaders, and the failClose is called on OnResponseBody. This seems problematic and unintended.
~This is WIP since I haven't passed Envoy tests.~
> Refactor around VM failure check on Http/Tcp callbacks.

- src/exports.cc
Previously, proxy_get_status() would return status message only when it was
called from the root context, which doesn't work when the effective context
is automatically changed to the calling context as part of the SDK.
With this change, status can be accessed from either root or child context.
> Allow access to status message from a child context.

- BUILD
- bazel/dependencies.bzl
- bazel/repositories.bzl
- include/proxy-wasm/wasm_api_impl.h
This was incorrectly removed in #170, but it's needed by NullVM plugins
that make gRPC calls (built with -DPROXY_WASM_PROTOBUF).
> Re-add protobuf dependency.

- include/proxy-wasm/context.h
This PR allows embedders to pass plugin_key for PluginBases in order for it to include host specific information (e.g. listener info in Envoy).
ref https://github.com/envoyproxy/envoy/pull/17243#issuecomment-876811383
> Pass plugin key from embedders to PluginBase.

- test/test_data/env.rs
This PR suppresses the warning by rustc: 
```
warning: attribute should be applied to a function or static
--> test/test_data/env.rs:15:1
|
15 |   #[no_mangle]
|   ^^^^^^^^^^^^
16 | / extern "C" {
17 | |     fn __wasilibc_initialize_environ();
18 | | }
| |_- not a function or static
|
= note: `#[warn(unused_attributes)]` on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
warning: 1 warning emitted
```
extern "c" already guarantee that the symbol remains un-mangled, so it is safe to remove it. Will make the same change to ~rust-sdk and~ Envoy tests.
> test: remove no_mangle from extern "c"

- include/proxy-wasm/exports.h
- include/proxy-wasm/wasm_api_impl.h
- include/proxy-wasm/wasm_vm.h
- src/exports.cc
- src/v8/v8.cc
- src/wamr/wamr.cc
- src/wasmtime/wasmtime.cc
- src/wavm/wavm.cc
- test/runtime_test.cc
This PR deletes unused raw_context arg in host functions which theoretically reduces the cost of each host calls from Wasm VMs.
> Delete unused raw_context arg in host functions.

- .github/workflows/cpp.yml
Fixes issues with addlicense requiring Go v1.16+.
> Use actions/setup-go@v2 in GitHub Actions.

- include/proxy-wasm/wasm.h
Fixes proxy-wasm/proxy-wasm-cpp-host#185.
> Make HTTP/gRPC callout IDs unique per WasmVM instance.

- include/proxy-wasm/exports.h
- include/proxy-wasm/wasm.h
- src/exports.cc
- src/wasm.cc
It seems unnecessary to have foreign functions managed by WasmBase because it's just using global lookup tables. 
> refactor: decouple foreign functions from WasmBase.

- include/proxy-wasm/exports.h
- include/proxy-wasm/wasm_vm.h
- src/exports.cc
Resolves #199 
This allows TinyGo apps to use `time.Time` struct (which is really commonly used).
> wasi: export stubs for preopened files and directories.

- bazel/repositories.bzl
> wasmtime: update C API to v0.32.0.

- bazel/external/wasmtime.BUILD
Helpers are already compiled by the build script in wasmtime-runtime
crate, which also sets some defines that were missing in Bazel rules
and broke build on Windows.
> wasmtime: rely on the build script to build helpers.

- .github/workflows/cpp.yml
- BUILD
- bazel/BUILD
- src/signature_util.cc
Use: bazel test --define crypto=system //test/...
> Allow using system's crypto library instead of BoringSSL.

- bazel/BUILD
- bazel/dependencies.bzl
- bazel/repositories.bzl
- bazel/wasm.bzl
> Fix rules_rust on Linux/s390x.

- bazel/repositories.bzl
> Update BoringSSL to 2022-01-10.

- bazel/external/wavm.patch
- bazel/repositories.bzl
> wavm: fix build with Clang 13.

- .github/workflows/cpp.yml
- bazel/cargo/Cargo.toml
- bazel/cargo/remote/BUILD.wasmtime-jit-0.33.0.bazel
> wasmtime: fix build on Linux/aarch64.

- .github/workflows/cpp.yml
> build: improve caching.

- .github/workflows/cpp.yml
rules_foreign_cc is automatically downloading CMake and Ninja.
> build: stop installing Ninja.

- include/proxy-wasm/exports.h
- include/proxy-wasm/wasm.h
- include/proxy-wasm/word.h
- src/exports.cc
- src/v8/v8.cc
- src/wamr/wamr.cc
- src/wasmtime/wasmtime.cc
- src/wavm/wavm.cc
- test/runtime_test.cc
Wasm binary always has Little-endian byte ordering. V8 is hardcoded to reverse the bytes with every wasm load/store operation done on Big-endian machines. But in case of envoy proxy the wasm binary file is linked with envoy C code compiled on a native BE machine. In this case a BE value is being written to LE enforced memory, and the crash happens when running wasm on BE machine. To fix this, everything needs to be written to memory in LE order when linking with any other libraries outside the wasm binary itself.
Resolves https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/197
> Add support for big-endian platforms.

- bazel/external/v8.patch
- bazel/repositories.bzl
- src/v8/v8.cc
- src/wamr/wamr.cc
- src/wasmtime/wasmtime.cc
- src/wavm/wavm.cc
- test/BUILD
- test/runtime_test.cc
> Fix segfault when failing to instantiate Wasm module.

- .github/workflows/cpp.yml
> ci: build test data only once.

- .github/workflows/cpp.yml
Cache updates on PRs result in early eviction of primary cache,
due to the limited quota on GitHub Actions.
While there, remove fallback to restore cache key based only on
the Wasm runtime name, since it prevents pruning of stale data.
> ci: skip cache update on PRs.

- bazel/repositories.bzl
> Update BoringSSL to 2022-02-07.

- .github/workflows/cpp.yml
Following proxy-wasm/proxy-wasm-cpp-host#239, it builds fast enough.
> ci: don't cache WAMR.

- .github/workflows/cpp.yml
- BUILD
- bazel/BUILD
- bazel/select.bzl
- include/proxy-wasm/context.h
- include/proxy-wasm/null_vm.h
- include/proxy-wasm/wasm_vm.h
- src/v8/v8.cc
- src/wamr/wamr.cc
- src/wasm.cc
- src/wasmtime/wasmtime.cc
- src/wavm/wavm.cc
- test/exports_test.cc
- test/null_vm_test.cc
- test/runtime_test.cc
- test/utility.cc
- test/utility.h
- test/wasm_test.cc
> Rename "runtime" to "engine".

- test/exports_test.cc
- test/runtime_test.cc
- test/utility.cc
- test/wasm_test.cc
While there, sort them alphabetically.
> test: print Wasm engine names in test logs.

- .bazelrc
- .github/workflows/cpp.yml
- include/proxy-wasm/exports.h
- include/proxy-wasm/word.h
- src/exports.cc
- src/signature_util.cc
- src/v8/v8.cc
- src/wamr/wamr.cc
- src/wasmtime/wasmtime.cc
- src/wavm/wavm.cc
- test/runtime_test.cc
Broken in proxy-wasm/proxy-wasm-cpp-host#198 due to lack of coverage.
> Fix build on Windows.

- BUILD
- bazel/external/wasm-c-api.BUILD
- bazel/select.bzl
- src/wasmtime/types.h
- src/wasmtime/wasmtime.cc
> wasmtime: split "prefixed_wasmtime" into a separate target.

- .bazelrc
- .github/workflows/test.yml
- test/BUILD
- test/runtime_test.cc
> build: add support for Clang with Address Sanitizer.

- .bazelrc
- .github/workflows/test.yml
- test/runtime_test.cc
> build: add support for Clang with Thread Sanitizer.

- .bazelrc
- BUILD
> build: move global copts/linkopts into specific targets.

- .github/workflows/format.yml
- .github/workflows/test.yml
> ci: fix broken dependencies.

- .github/workflows/test.yml
- src/v8/v8.cc
- src/wasmtime/wasmtime.cc
Broken in proxy-wasm/proxy-wasm-cpp-host#217.
> wasmtime: fix params array getting out of scope.

- BUILD
- src/exports.cc
- src/wasm.cc
- test/BUILD
- test/runtime_test.cc
- test/wasm_vm_test.cc
> test: move WasmVm tests into wasm_vm_test.

- include/proxy-wasm/context.h
- test/exports_test.cc
- test/utility.h
Signed-off-by: chaoqin-li1123 <chaoqinli@google.com>
> Remove default implementations from headers.

- bazel/external/v8.patch
- bazel/repositories.bzl
> v8: update to v10.0.139.6.

- .github/workflows/test.yml
- BUILD
- bazel/BUILD
- bazel/external/wasmedge.BUILD
- bazel/repositories.bzl
- bazel/select.bzl
- include/proxy-wasm/wasmedge.h
- src/wasmedge/types.h
- src/wasmedge/wasmedge.cc
- test/utility.cc
- test/utility.h
- test/wasm_vm_test.cc
Hi,
Here's the maintainer of the [WasmEdge](https://github.com/WasmEdge/WasmEdge) runtime.
This pull request implements the WasmEdge supporting for the proxy-wasm with the newest WasmEdge release version (0.8.2).
For this first version, we provides the interpreter mode of WASM runtime, and the AOT mode supporting for proxy-wasm is still work in progress.
Please feel free to review this pull request and give us some advices if there's issues, bugs, or incomplete implementations.
Thank you.
Resolves #97
> wasmedge: add support for WasmEdge engine.

- include/proxy-wasm/limits.h
- src/exports.cc
- test/BUILD
- test/exports_test.cc
- test/test_data/BUILD
- test/test_data/random.rs
With this change, random_get will return an error for buffers larger than 64kB.
This is consistent with the JavaScript Crypto.getRandomValues() maximum buffer size.
> Bound maximum size of random_get buffer.

- bazel/repositories.bzl
- src/wasmedge/types.h
- src/wasmedge/wasmedge.cc
Signed-off-by: YiYing He <yiying@secondstate.io>
> wasmedge: update to 0.10.0.

- src/exports.cc
While there, make sure to write a return pointer and length
when returning an empty buffer.
Reported by Chris Ertl from Google Security.
> Don't overread buffers.

- bazel/BUILD
In a future version of bazel visibility on config_settings will be enforced. This allows these to be used by anyone.
https://github.com/envoyproxy/envoy/issues/23390
> Add default visibility to Bazel's config_settings.

- .github/workflows/test.yml
- BUILD
- bazel/external/wasmedge.BUILD
- bazel/repositories.bzl
- src/wasmedge/wasmedge.cc
* Update WasmEdge to 0.11.2.
* Support MacOS x86_64.
> wasmedge: update to v0.11.2.

- bazel/wasm.bzl
Starting with v1.61 rust s390x package contains rust-lld
> rustc_flags linker flag no longer needed for s390x

- src/wamr/wamr.cc
Reuse `bytecode` instead of creating and copy the binary content during `wasm_byte_vec_new()`
> wamr: avoids .wasm binary content copying.

- bazel/repositories.bzl
```
WARNING: Download from https://git.sr.ht/~motiejus/bazel-zig-cc/archive/v0.4.4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was b3dd78971f0f831f62d84ae96656bdb0941b91b7c80097d69f5be213351cc6ff but wanted ad6384b4d16ebb3e5047df6548a195e598346da84e5f320250beb9198705ac81
```
> Fix a checksum exception about bazel-zig-cc.

- bazel/external/wamr.BUILD
- bazel/external/wamr_llvm.BUILD
- bazel/repositories.bzl
- src/wamr/wamr.cc
- bump llvm to 15.0.7
- bump wamr to 1.2.1
> wamr: update to v1.2.1 (with LLVM v15.0.7).

- include/proxy-wasm/wasm.h
- src/wasm.cc
- test/wasm_test.cc
> Cache canary results.

- bazel/repositories.bzl
The current wasmtime version has a CVE version showing https://github.com/envoyproxy/envoy/issues/27422
Historically updating wasmtime here has required updating rules_rust so i have broken out the update here
> Update rules_rust to v0.22.0 (with Rust v1.69.0).

- .github/workflows/format.yml
- .github/workflows/test.yml
Currently workflows in this repo (which take a huge amount of time) continue when new commits are pushed to PRs
This will autocancel existing runs for PRs
> Auto-cancel old GitHub Actions workflows.

- CODEOWNERS
To clarify my position, this PR removes me from CODEOWNERS. 
I must admit this should've happened much earlier. Sorry about that.
> Remove @mathetake from CODEOWNERS.

- src/wasm.cc
Since VM and plugin thread-local cache keys include volatile parts (namely VM configuration, code and plugin configuration), their reconfiguration/update (e.g. with Envoy ADS protocol) might lead to memory leak by leaving those thread-local map stale keys behind. The current cleanup method is insufficient, as it accounts only for cache hit case.
Also, plugin configuration is placed into cache key as is (by contrast with SHA256 hash for VM keys), which causes noticeable memory consumption when configuration is large.
> Fix memory leak in thread-local VM & plugin caches

- BUILD
- src/wasm.cc
- src/wasm.h
- test/wasm_test.cc
Tests for #357. Sorry for not making them in time in original PR 😅
> Added tests for thread-local caches cleanup.

- BUILD
- include/proxy-wasm/context.h
- include/proxy-wasm/context_interface.h
- include/proxy-wasm/pairs_util.h
- include/proxy-wasm/sdk.h
- include/proxy-wasm/vm_id_handle.h
- include/proxy-wasm/wasm.h
- include/proxy-wasm/wasm_api_impl.h
- include/proxy-wasm/wasm_vm.h
- include/proxy-wasm/word.h
- test/fuzz/pairs_util_fuzzer.cc
fixes https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/364
- include: add missing dependencies 
- fix: proxy_wasm namespace polution with std defs 
- include: add missing includes to pairs_util and the test 
```
In file included from external/proxy_wasm_cpp_host/src/null/null.cc:17:
In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/null_vm.h:22:
In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/null_vm_plugin.h:18:
In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/wasm_vm.h:26:
In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/word.h:22:
external/proxy_wasm_cpp_sdk/proxy_wasm_common.h:59:8: error: no type named 'string' in namespace 'proxy_wasm::std'; did you mean '::std::string'?
inline std::string …
```
> fix a few missing includes and ::proxy_wasm namespace pollution with std {}

- bazel/external/v8_include.patch
- bazel/repositories.bzl
Copy changes from envoyproxy/envoy#29425.
This is a temporary build fix until #382 (major v8 upgrade, 10.7 -> 12.0).
> v8: add missing <cstdint> includes.

- BUILD
- bazel/repositories.bzl
Fixes build warning-as-error:
```
external/boringssl/src/crypto/x509/t_x509.c:326:18: error: variable 'l' set but not used [-Werror,-Wunused-but-set-variable]
int ret = 0, l, i;
^
```
> Update BoringSSL to 2023-08-28.

- bazel/repositories.bzl
Pick up this fix: https://github.com/abseil/abseil-cpp/pull/1187
Bump to latest LTS version (past Envoy) to pick up another fix found in local fuzz tests:
https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/399#issuecomment-2261871275
Build issue seen on:
```
$ /usr/lib/llvm-16/bin/clang --version
Debian clang version 16.0.6 (26)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-16/bin
```
> fix: Bump Abseil to fix Linux build issues

- .github/workflows/test.yml
See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
This does not fix #384, but does resurface those errors.
> fix: Move CI from unavailable macos-11 to macos-13

- WORKSPACE
- bazel/dependencies.bzl
- bazel/dependencies_import.bzl
- bazel/dependencies_python.bzl
- bazel/external/v8.patch
- bazel/repositories.bzl
Fixes macOS CI https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/384
Upgrade rules_python (0.34.0) and rules_fuzzing (0.5.2)
This requires extracting more WORKSPACE phases:
- dependencies -- py_repositories() and toolchains
- dependencies_python() -- pip_parse module loading
- dependencies_import() -- python/fuzzing/other deps
The new structure roughly matches Envoy WORKSPACE:
- envoy_dependencies()
- envoy_dependencies_extra() -- not needed here
- envoy_python_dependencies()
- envoy_dependency_imports()
> chore: bump rules_python and rules_fuzzing

- .github/workflows/test.yml
Seen on https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/380 CI:
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Fixes https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/416
> fix: Upgrade deprecated artifact upload/download handlers

- bazel/external/wasmtime.BUILD
References to `include/wasm.h` changed to `crates/c-api/include/wasm.h`, so the prefixed api output needs to change as well. Fixes #418
> Fix references to prefix_wasm_api

- .github/workflows/format.yml
- .github/workflows/test.yml
- include/proxy-wasm/signature_util.h
- Update format workflows to use ubuntu-22.04
- Enable manual triggering of workflows
Fixes #435
> chore: workflow runner fixes

- CODEOWNERS
Matt is on the same team as existing owners @martijneken and @mpwarres, knows the proxy-wasm-cpp-host codebase well, and having the additional owner will be helpful in reviving update velocity.
> add leonm1@ to CODEOWNERS

- bazel/cargo/wasmsign/Cargo.toml
- bazel/cargo/wasmtime/Cargo.toml
- bazel/external/Dockerfile.bazel
- bazel/external/dragonbox.BUILD
- bazel/external/fp16.BUILD
- bazel/external/intel_ittapi.BUILD
- bazel/external/llvm.BUILD
- bazel/external/simdutf.BUILD
- bazel/external/wamr.BUILD
- bazel/external/wamr_llvm.BUILD
- bazel/external/wasmedge.BUILD
- bazel/external/wasmtime.BUILD
addlicense v1.2.0 supports linting .BUILD files, so the verify licenses check will fail for all future PRs without this commit.
https://github.com/google/addlicense/releases/tag/v1.2.0
> chore: Add license headers to BUILD files

- .github/workflows/test.yml
Caches are growing organically (started around 400MiB, now at 2+GiB). This strategy is used by github.com/GoogleCloudPlatform/service-extensions to evict unneeded cached entries.
> workflows: remove unaccessed files from cache before saving

- .github/workflows/format.yml
- .github/workflows/test.yml
Modify proxy-wasm-cpp-host Github actions that previously ran on stock ubuntu-24.04 runner to instead use a newly provisioned larger runner instance, with 16 cores, 64GB RAM, and 600GB SSD.
Should fix #457.
> chore: execute proxy-wasm-cpp-host ubuntu-24.04 actions on larger runner
