proxy-wasm/proxy-wasm-cpp-host

src/wasm.cc
=> Add missing constructor values.

.github/workflows/cpp.yml
=> Add github workflow.

include/proxy-wasm/wasm.h
=> Fix asan issue.

BUILD, include/proxy-wasm/context.h, include/proxy-wasm/context_interface.h, include/proxy-wasm/null_plugin.h, src/context.cc, src/exports.cc, src/null/null_plugin.cc, src/wasm.cc
The corresponding proxy-wasm PR is forthcoming.
=> Incorporate review comments from the context header review.

include/proxy-wasm/context.h, include/proxy-wasm/context_interface.h
=> Remove ContextInterface.

src/exports.cc
if the foreign function returns no results.
=> Handle foreign results null pointers as non-errors

src/context.cc
=> Add implmeneation of resolveQueueForTesting.

WORKSPACE, include/proxy-wasm/context.h, include/proxy-wasm/context_interface.h, include/proxy-wasm/exports.h, include/proxy-wasm/wasm_api_impl.h, src/exports.cc, src/null/null_plugin.cc, src/wasm.cc
=> Add support for closing of connections in the ABI/SDK.

src/wasm.cc
=> Ensure that we report cloning failures.

src/foreign.cc
=> Use string_view instead of absl::string_view.

.github/workflows/cpp.yml
=> Enable GitHub Actions for envoy-release/** branches.

include/proxy-wasm/context_interface.h, include/proxy-wasm/wasm_vm.h, src/v8/v8.cc, src/wavm/wavm.cc
=> Add missing optional include.

include/proxy-wasm/null_plugin.h
=> Add a missing symbol for 0_2_1 version

src/v8/v8.cc
=> Fix C++14 compatibility.

.bazelrc, BUILD, include/proxy-wasm/context.h, include/proxy-wasm/wasm_vm.h
=> Windows build fixes.

src/null/null_plugin.cc
=> Fix an integer coersion that bothers VC++.

WORKSPACE, include/proxy-wasm/context_interface.h, src/null/null_plugin.cc
=> Fixup onLog for null vm for non-stream (Root) context.

src/exports.cc
=> Fix return values.

include/proxy-wasm/context.h, include/proxy-wasm/wasm.h, src/context.cc, src/wasm.cc
This reverts commit f08baacadbe656674414f0878e18852bed67b795.
=> Revert "Allow execution of multiple instances of the same plugin. (#78)"

src/wasm.cc
=> Add better logging for a few common errors.

src/v8/v8.cc
=> v8: fix error message for function signature mismatch.

.github/workflows/cpp.yml
=> Run GitHub Actions on istio-release/** branches. (#102)

src/context.cc
=> Always process HTTP headers before processing HTTP body. (#95)

src/context.cc, src/shared_data.cc, src/shared_data.h, src/shared_queue.cc, src/shared_queue.h, src/vm_id_handle.cc, test/shared_queue_test.cc
first two commits are cherry picked from #114
=> Fix global VmIdHandles initialization fiasco and build failure 

include/proxy-wasm/null_plugin.h, include/proxy-wasm/wasm_vm.h, src/v8/v8.cc, src/wasmtime/wasmtime.cc, src/wavm/wavm.cc, test/runtime_test.cc
ref: https://github.com/envoyproxy/envoy/pull/14107#issuecomment-739711288
=> Add strace equivalent on ABI boundary.

CODEOWNERS
=> Add @mathetake to CODEOWNERS.

include/proxy-wasm/wasm.h, src/wasm.cc
=> Pass PluginBase to PluginHandleFactory.

.github/workflows/cargo.yml
=> Remove freshness check for Cargo.raze.lock.

bazel/repositories.bzl
=> wavm: update to nightly/2021-05-10.

include/proxy-wasm/wasm_vm.h, src/wasm.cc
=> style: rename VM->Vm in FailState enum.

src/wasm.cc
=> Delete unused INLINE_STRING.

include/proxy-wasm/wasm_vm.h
rescued https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/164
=> Fix the doc comment for WasmVm::runtime.

bazel/external/wasmtime.BUILD, bazel/repositories.bzl, bazel/wasm.bzl
=> Update rules_rust to latest (with Rust v1.57.0).

bazel/dependencies.bzl, bazel/repositories.bzl
=> Update rules_rust to latest (with Rust v1.58.1).

bazel/external/llvm.BUILD, bazel/external/llvm13.BUILD, bazel/external/wavm.BUILD, bazel/repositories.bzl
=> Update rules_foreign_cc to v0.7.1.

.github/workflows/cpp.yml, bazel/external/wasmtime.BUILD
=> build: increase reach of the buildifier check.

.github/workflows/cpp.yml, src/signature_util.cc
=> Fix Wasm signature verification on big-endian platforms.

bazel/repositories.bzl
=> v8: update to v10.0.101.

.bazelrc, .github/workflows/cpp.yml, bazel/cargo/wasmtime/Cargo.toml, bazel/cargo/wasmtime/crates.bzl, bazel/cargo/wasmtime/psm.patch, bazel/dependencies.bzl, bazel/external/rules_rust.patch, bazel/repositories.bzl
This is all very bleeding edge, so many fixes are required.
Wasmtime builds fine now, but no luck with the test data.
=> build: fix building Rust build scripts with Zig C/C++ compiler.

.bazelrc
=> build: add config for GCC compiler.

.github/workflows/cpp.yml
=> ci: get Bazel's output paths from within Docker.

.github/workflows/cpp.yml
=> ci: add daily run to prevent primary cache from expiring.

src/v8/v8.cc
=> v8: add missing namespace.

.github/workflows/test.yml
=> ci: fix caching of builds with sanitizers.

src/v8/v8.cc
=> Avoid thread-unsafe host integration call in terminate().

src/wasm.cc, test/BUILD, test/exports_test.cc, test/runtime_test.cc, test/test_data/callback.rs, test/test_data/clock.rs, test/test_data/env.rs, test/test_data/infinite_loop.rs, test/test_data/trap.rs, test/utility.h, test/wasm_test.cc
While there, change the default integration log level in tests to trace.
=> test: use a bit more realistic flow in tests.

BUILD, bazel/BUILD, bazel/external/BUILD, test/BUILD, test/fuzz/BUILD, test/test_data/BUILD
Signed-off-by: Ryan Northey <ryan@synca.io>
=> Add license headers to BUILD files.

bazel/repositories.bzl
=> wasmedge: update to v0.13.1.

.github/workflows/test.yml, bazel/dependencies.bzl, bazel/external/Dockerfile.bazel
This fixes https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/405
=> chore: Update CI to use Ubuntu 22.04 / clang 14
